// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCMfu79xqUTFvw0sf2TZx6-4EqD3q0T3c',
    appId: '1:477342638812:web:9679c9818db86848140a19',
    messagingSenderId: '477342638812',
    projectId: 'aihealth-440ed',
    authDomain: 'aihealth-440ed.firebaseapp.com',
    storageBucket: 'aihealth-440ed.firebasestorage.app',
    measurementId: 'G-0DCBQ8GEBX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARb-cUnqvXO4ZoKFsMENkBA_g13qcrqLY',
    appId: '1:477342638812:android:491b3a0f2c024447140a19',
    messagingSenderId: '477342638812',
    projectId: 'aihealth-440ed',
    storageBucket: 'aihealth-440ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp8q_Giorcy6HRBJdFF9CcUda1j6jeFQo',
    appId: '1:477342638812:ios:5aa45bc89e639183140a19',
    messagingSenderId: '477342638812',
    projectId: 'aihealth-440ed',
    storageBucket: 'aihealth-440ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp8q_Giorcy6HRBJdFF9CcUda1j6jeFQo',
    appId: '1:477342638812:ios:5aa45bc89e639183140a19',
    messagingSenderId: '477342638812',
    projectId: 'aihealth-440ed',
    storageBucket: 'aihealth-440ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCMfu79xqUTFvw0sf2TZx6-4EqD3q0T3c',
    appId: '1:477342638812:web:2d1d875533557c79140a19',
    messagingSenderId: '477342638812',
    projectId: 'aihealth-440ed',
    authDomain: 'aihealth-440ed.firebaseapp.com',
    storageBucket: 'aihealth-440ed.firebasestorage.app',
    measurementId: 'G-60Q5LRJ51G',
  );
}
